### ISSUE TITLE
Method not found: 'Void OpenQA.Selenium.Edge.EdgeOptions.AddExtensionPath(System.String)'.

### ISSUE THREAD

**Issue by Fantom579** [mahdibland/Selenium-Proxy-Authentication.Chrome#1]
Method not found: 'Void OpenQA.Selenium.Edge.EdgeOptions.AddExtensionPath(System.String)'.

**Comment by mahdibland** [comment]
it's because that function was removed from the WebDriver library version 4.x.x
I will put an updated version for the edge browser soon
